package com.orbitworkbench.shared.api;

public enum ErrorCode {
    VALIDATION_FAILED,
    UNAUTHENTICATED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    STATE_CONFLICT,
    DUPLICATE_REQUEST,
    AUTHENTICATION_FAILED,
    MODEL_NOT_FOUND,
    UNSUPPORTED_CAPABILITY,
    RATE_LIMITED,
    REQUEST_TIMEOUT,
    UPSTREAM_UNAVAILABLE,
    INVALID_REQUEST,
    INVALID_STRUCTURED_OUTPUT,
    OUTPUT_LIMIT_EXCEEDED,
    STREAM_INTERRUPTED,
    CANCELLED,
    UNKNOWN_PROVIDER_ERROR,
    FILE_TOO_LARGE,
    UNSUPPORTED_MEDIA_TYPE,
    INVALID_STORAGE_PATH,
    FILE_NOT_FOUND
}
